# Generated by Django 2.1.2 on 2018-10-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecsinfo',
            old_name='hostame',
            new_name='hostname',
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='instanceId',
            field=models.CharField(db_column='instance_id', max_length=255, unique=True),
        ),
    ]
