# Generated by Django 2.1.2 on 2018-11-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181031_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='EipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocationId', models.CharField(db_column='allocation_id', max_length=255)),
                ('allocationName', models.CharField(db_column='allocation_name', max_length=255)),
                ('instanceId', models.CharField(db_column='instance_id', max_length=255)),
                ('instanceType', models.CharField(db_column='instance_type', max_length=255)),
                ('productCode', models.CharField(db_column='product_code', max_length=255)),
                ('businessLine', models.CharField(db_column='business_line', max_length=255)),
                ('env', models.CharField(db_column='env', max_length=255)),
                ('ipaddress', models.CharField(db_column='ipaddress', max_length=255)),
                ('regionId', models.CharField(db_column='region_id', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('creationTime', models.CharField(db_column='create_time', max_length=255)),
                ('expiredTime', models.CharField(db_column='expired_time', max_length=255)),
                ('remark', models.CharField(db_column='remark', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RdsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(db_column='instance_id', max_length=255)),
                ('instanceName', models.CharField(db_column='instance_name', max_length=255)),
                ('productCode', models.CharField(db_column='product_code', max_length=255)),
                ('businessLine', models.CharField(db_column='business_line', max_length=255)),
                ('env', models.CharField(db_column='env', max_length=255)),
                ('regionId', models.CharField(db_column='region_id', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('instanceNetworkType', models.CharField(db_column='instance_networktype', max_length=255)),
                ('publicIpAddress', models.CharField(db_column='public_ipaddress', max_length=255)),
                ('primaryIpAddress', models.CharField(db_column='primary_ipaddress', max_length=255)),
                ('cpuMemory', models.CharField(db_column='cpu_memory', max_length=255)),
                ('engine', models.CharField(db_column='engine', max_length=255)),
                ('instanceType', models.CharField(db_column='instance_type', max_length=255)),
                ('masterInstanceId', models.CharField(db_column='master_instanceid', max_length=255)),
                ('guardDBInstanceId', models.CharField(db_column='guarddb_instanceid', max_length=255)),
                ('readOnlyDBInstanceId', models.CharField(db_column='readonlydb_instanceid', max_length=255)),
                ('creationTime', models.CharField(db_column='create_time', max_length=255)),
                ('expiredTime', models.CharField(db_column='expired_time', max_length=255)),
                ('remark', models.CharField(db_column='remark', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(db_column='instance_id', max_length=255)),
                ('instanceName', models.CharField(db_column='instance_name', max_length=255)),
                ('productCode', models.CharField(db_column='product_code', max_length=255)),
                ('businessLine', models.CharField(db_column='business_line', max_length=255)),
                ('env', models.CharField(db_column='env', max_length=255)),
                ('regionId', models.CharField(db_column='region_id', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('instanceNetworkType', models.CharField(db_column='instance_networktype', max_length=255)),
                ('internetChargeType', models.CharField(db_column='internet_chargeType', max_length=255)),
                ('ipaddress', models.CharField(db_column='ipaddress', max_length=255)),
                ('BackendServers', models.CharField(db_column='backend_servers', max_length=255)),
                ('ListenPorts', models.CharField(db_column='listen_ports', max_length=255)),
                ('creationTime', models.CharField(db_column='create_time', max_length=255)),
                ('expiredTime', models.CharField(db_column='expired_time', max_length=255)),
                ('remark', models.CharField(db_column='remark', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ecsinfo',
            name='instanceId',
            field=models.CharField(db_column='instance_id', max_length=255),
        ),
    ]
