# Generated by Django 2.1.3 on 2018-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_monthlybillinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingCycle', models.CharField(db_column='month', max_length=255)),
                ('productName', models.CharField(db_column='product_name', max_length=255)),
                ('businessLine', models.CharField(db_column='business_line', max_length=255)),
                ('env', models.CharField(db_column='env', max_length=255)),
                ('pretaxAmount', models.FloatField(db_column='pretax_amount', max_length=255)),
                ('instanceTotals', models.IntegerField(db_column='instance_totals')),
                ('remark', models.CharField(db_column='remark', max_length=255)),
            ],
        ),
    ]
